// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
// The first ten pentagonal numbers are:

// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
// difference, 70 − 22 = 48, is not pentagonal.

// Find the pair of pentagonal numbers, Pj and Pk, for which their
// sum and difference are pentagonal and D = |Pk − Pj| is minimised;
// what is the value of D?

package main

import "fmt"

func pentagonal(n int) int {
	return (3*n*n - n) / 2
}

func main() {
	isPentagonal := make(map[int]bool)
	pmap := make(map[int]int)

	for i := 1; i <= 1000000; i++ {
		isPentagonal[pentagonal(i)] = true
		pmap[i] = pentagonal(i)
	}

loop:
	for d := 1; d <= 100000; d++ { // d is distance b/n numbers picked
		for i := 1; i < 2000; i++ { // i is index of number picked
			if _, ok := isPentagonal[pmap[i+d]-pmap[i]]; ok {
				if _, ok2 := isPentagonal[pmap[i+d]+pmap[i]]; ok2 {
					fmt.Println(pmap[i+d] - pmap[i]) // 5482660
					break loop
				}
			}
		}
	}
}
